# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Xeeeeon Blog"
weight = 1

[zh-CN]
languageName = "Chinese"
languagedirection = "ltr"
title = "xq_work@outlook.com"
weight = 1
